Guy camps issue#80
Midburn/spark pull request #100
Opened 2017-02-06 12:08 UTC by guywarburg

Fixes #80  

Added missing translation keys for camp details and new camp page.
Improved 'new camp modal' design to allow translation.
Modal shows only fields with values.

TODO:
Fix dropdown values - they always show in english.
Camp Type checkboxes always returns undefined.

Tested 'npm test' successfully. Validated that all fields show both in Hebrew and English and that the data matches the correct value.

2017-02-09 07:50 UTC, netanelben requested changes
Guy, can you split the camps.js logic and translated templates into saparte branch's?

2017-02-10 19:28 UTC, guywarburg commented
Reverted two last commits (modal fix)
This branch now contains only translation fixes.

2017-02-15 17:52 UTC, OriHoch approved these changes

2017-02-15 21:31 UTC, netanelben reviewed
Great!

2017-02-15 21:31 UTC, netanelben approved these changes

2017-02-15 21:41 UTC, merged