Breadcrumbs Enabled In All of Spark
Midburn/spark pull request #137
Opened 2017-03-07 16:16 UTC by guywarburg

### Proposed solution
Closes #127 - Added breadcrumbs to whole website.

### Tradeoffs
Accidentally branched out of a local branch so made some extra changes to revert those.

### Testing Done
Tests pass.

2017-03-07 18:46 UTC, guywarburg commented
I would like to us the feature:
`breadcrumbs.setHome()` so I can clean up the code.
However, is this is set up before any request is made I don't have access to the language.
I wanted to ask if there's another place where I can access the user's language - some sort of cookie or another way?

In used `req.params.lng` but as we aren't in the scope of a specific request I can't access that and looking for an alternative.

2017-03-08 06:38 UTC, OriHoch approved these changes
nice!

2017-03-08 06:41 UTC, OriHoch commented
@guywarburg - about your question regarding accessing req.params.lng - 

I'm not familiar with `breadcrumbs.setHome()` - but, IIUC - this function runs in a scope that doesn't have access to req object. 
Does the req object exist while it's running but it just doesn't have access to it? or - it doesn't exist yet at all?

I think the best way is to make sure req object exists while this function runs and also make sure it has access to it (worst case scenario - via a global variable)

2017-03-08 07:56 UTC, guywarburg commented
@OriHoch - I tried to initiate the `setHome()` within the first `.get()` call to the server but it doesn't work there (not sure why). It must be set-up immediately after `breadcrumbs.init()` (main_routes.js line 21). This is before any requests have been made so we can't specify a language (or at least as far as I know).
In second thought, maybe the better idea is to set the default language according to a cookie and not just hard coded Hebrew. Once this is set up the home breadcrumb url will be set simply to '/' and the routes will add the language according to the user's choice.

2017-03-15 16:03 UTC, natekonimbo commented
awesome!

2017-03-20 16:43 UTC, guywarburg commented
All tests passed locally - this is odd

2017-03-24 14:00 UTC, LeonFedotov commented
@guywarburg it seems like part of the implementation is there on master, is this pr still relevant? if so please merge from master.

2017-03-24 14:35 UTC, guywarburg commented
@LeonFedotov - the idea was to add the breadcrumbs across the board (to all pages).
I'll fix it soon, it's the 2nd time it isn't merged in time so it creates conflicts...

2017-03-24 15:02 UTC, LeonFedotov commented
Yes i see the conflicts, i went over them and there are some stuff that has
been already added to master, maybe you can try to merge master to your
branch and see if the new changes fit your solution:)
On Fri, 24 Mar 2017 at 17:35 Guy Warburg <notifications@github.com> wrote:

> @LeonFedotov <https://github.com/LeonFedotov> - the idea was to add the
> breadcrumbs across the board (to all pages).
> I'll fix it soon, it's the 2nd time it isn't merged in time so it creates
> conflicts...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Midburn/Spark/pull/137#issuecomment-289039614>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAH9JmDGr09TWqU-KmncBE05X06yGsbPks5ro9SjgaJpZM4MVsMR>
> .
>
-- 
Leon. Everything web.
leonfedotov.com

2017-03-26 23:07 UTC, LeonFedotov requested changes

2017-03-26 23:07 UTC, LeonFedotov commented on views/pages/camps/camp.jade
> +<<<<<<< HEAD
hey @guywarburg i think you got a situation here

2017-03-26 23:07 UTC, LeonFedotov commented on routes/camps_routes.js
> +                    details: camp.related('details').toJSON(),
this is a duplicate key

2017-03-26 23:07 UTC, LeonFedotov commented on routes/camps_routes.js
> +                camp: camp.toJSON(),
this is another duplicate key

2017-03-27 09:12 UTC, guywarburg commented
@LeonFedotov - fixed duplicates and improved breadcrumbs for new flow

2017-03-27 09:22 UTC, LeonFedotov approved these changes
looks good

2017-03-27 18:06 UTC, amotenko commented
@guywarburg it seems like there are minor conflicts that are not your fault, can you please sort them so I'll be able to merge

2017-03-27 19:48 UTC, guywarburg commented
@amotenko - fixed please merge

2017-03-27 20:05 UTC, merged